FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY docker/maven/settings.xml /root/.m2/settings.xml
COPY . .
ARG SERVICE
RUN --mount=type=cache,target=/root/.m2/repository \
    mvn -s /root/.m2/settings.xml -pl ${SERVICE} -am -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
ARG SERVICE
COPY --from=build /workspace/${SERVICE}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
